language: go

branches:
  only:
    - develop
    - main
    - release

env:
  - GO111MODULE=on

before_install:
  - echo "move"
  - mv $HOME/gopath/src/github.com/fghpdf/thunes_sample $HOME/gopath/src

script:
  - cd $HOME/gopath/src/thunes_sample
  - echo "unit test"
  - make unittest
  - echo "unit test coverage"
  - make coverage
  - echo "integration test"
  - make integration_test

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: release