language: go

branches:
  only:
    - develop
    - main
    - release

env:
  - GO111MODULE=on

before_install:
  - echo "unit test"
  - make unittest

script:
  - echo "unit test coverage"
  - make coverage